version: "3"
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    # network_mode: bridge
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    env_file: ./mysql.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: passwdstrong
    #   MYSQL_USER: user1
    #   MYSQL_PASSWORD: passwdstrong1

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/redis.conf
    # network_mode: bridge
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    # network_mode: bridge
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file: ./pgsql.env
    # environment:
    #   POSTGRES_USER: user
    #   POSTGRES_PASSWORD: passwdstrong

networks:
  default:
    external:
      name: bridge
