version: '3.3'
services:
    portainer-ee:
        ports:
            - '9443:9443'
        container_name: portainer
        restart: always
        # network_mode: bridge
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        image: portainer/portainer-ee