version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - "10.10.0.1:5380:5380/tcp" #DNS web console
      - "10.10.0.1:53:53/udp" #DNS service
      - "10.10.0.1:53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
    volumes:
      - ./config:/etc/dns/config
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000