version: '3.3'
services:
    watchtower:
        container_name: watchtower
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
        image: containrrr/watchtower
        # network_mode: bridge
        restart: always
        command:
            - '--cleanup'
            - '-s'
            - '0 0 */1 * * *'
