version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - 19132:19132/udp
    volumes:
      - ./bedrock_data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.16.5"
      RCON_PASSWORD: "password"
      MEMORY: "2G"
    ports:
      - "25565:25565"
    volumes:
      - ./java_data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped