version: "3"
services:

  outline:
    image: outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
     - 80:80
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redisdata:/data
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    # ports:
    #   - 127.0.0.1:5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline

  storage:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    env_file: ./docker.env
    command: minio server /data --console-address 0.0.0.0:9001
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  storage-data:
  database-data:
