version: "3"
services:
  derper:
    container_name: derper
    restart: always
#     build:
#       context: .
#       dockerfile: Dockerfile
    image: adobe17/derper:latest
    ports:
      - 443:443/tcp
      - 3478:3478/udp
    volumes:
      - <certdir>:/app/certs
      # - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock # For `-verify-clients` option
    command:
      -hostname derp.example.com
      -certdir /app/certs
      -certmode manual
      -a :443
      -stun-port 3478
      -http-port -1
      -verify-clients
