version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # for docker monitor
    ports:
      - 10.10.0.1:3001:3001  # <Host Port>:<Container Port>
    restart: always