name: Custom DERPer Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: adobe17/derper:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
#       - 
#         name: Clone Git Repo
#         run: |
#           git clone https://github.com/1itt1eB0y/MyCollection.git
#           mv MyCollection/docker/derper/* ./
#           rm -rf MyCollection
#           ls
#           pwd
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ secrets.DOCKER_HUB_USER }}/derper
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/derper/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: adobe17/derper:latest
