name: JasonCrack AutoBuild

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 */7 * *"

env:
  TEST_TAG: 1itt1eb0y/jsoncrack:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
#       -
#         name: Clone Git Repo
#         run: |
#          git clone https://github.com/AykutSarac/jsoncrack.com.git
#          mv jsoncrack.com/* ./
#          rm -rf MyCollection
#          ls
#          pwd
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/1itt1eb0y/jsoncrack
      - 
        name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker/jsoncrack/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            1itt1eb0y/jsoncrack:latest
            1itt1eb0y/jsoncrack:${{ steps.time.outputs.time }}
